# Generated by Django 4.1.2 on 2022-11-15 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wallettransactions_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.wallettransactions'),
        ),
    ]
