# Generated by Django 4.1.2 on 2022-11-15 06:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_accounts_wallet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wallet',
            name='Transactions',
        ),
        migrations.AddField(
            model_name='wallettransactions',
            name='wallet',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.wallet'),
        ),
    ]
