# Generated by Django 4.1.2 on 2022-11-16 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_wallet_transactions_wallettransactions_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='device',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
