# Generated by Django 4.1.2 on 2022-11-17 01:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_wallet_accounts_device_wallettransactions_and_more'),
        ('accounts', '0006_remove_accounts_wallet_wallet_user_and_more'),
    ]

    operations = [
    ]
