# Generated by Django 4.1.2 on 2022-11-17 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_remove_accounts_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='device',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
