# Generated by Django 4.1.2 on 2022-11-17 01:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_accounts_device'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='device',
        ),
    ]
