# Generated by Django 4.1 on 2022-10-20 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_rename_price_product_rice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='rice',
            new_name='price',
        ),
    ]
