# Generated by Django 4.1.2 on 2022-11-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_coupen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupen',
            name='discount_price',
            field=models.IntegerField(default=100),
        ),
    ]
