# Generated by Django 4.1.2 on 2022-11-07 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0007_alter_coupen_discount_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='offer',
            field=models.CharField(default=0, max_length=255),
        ),
        migrations.AddField(
            model_name='coupen',
            name='offer',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
