# Generated by Django 4.1.2 on 2022-11-07 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0008_category_offer_coupen_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(default=0, max_length=255),
        ),
    ]
