# Generated by Django 4.1.2 on 2022-11-08 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adminapp', '0011_alter_category_offer_alter_coupen_offer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupen',
            name='customer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='coupon', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='category',
            name='offer',
            field=models.IntegerField(default=0),
        ),
    ]
