# Generated by Django 4.1.2 on 2022-11-08 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0012_coupen_customer_alter_category_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupen',
            name='offer',
        ),
    ]
