# Generated by Django 4.1.2 on 2022-11-08 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0013_remove_coupen_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupen',
            name='customer',
        ),
    ]
