# Generated by Django 4.1.2 on 2022-10-28 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0003_address_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='address',
            name='address_type',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='address',
            name='default_address',
        ),
        migrations.RemoveField(
            model_name='address',
            name='state',
        ),
    ]
