# Generated by Django 4.1.2 on 2022-10-31 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0006_remove_order_cart_remove_order_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_delivered',
            field=models.DateField(default='2022-01-01'),
        ),
    ]
