# Generated by Django 4.1.2 on 2022-10-31 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0007_alter_order_date_delivered'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_no',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
