# Generated by Django 4.1.2 on 2022-10-31 17:32

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0008_order_tracking_no'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Order',
            new_name='OrderTable',
        ),
    ]
