# Generated by Django 4.1.2 on 2022-11-05 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0006_coupen'),
        ('userapp', '0013_coupen'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Coupen',
        ),
        migrations.AddField(
            model_name='cart',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminapp.coupen'),
        ),
    ]
