# Generated by Django 4.1.2 on 2022-11-10 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0014_delete_coupen_cart_coupon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled')], default='Pending', max_length=100),
        ),
    ]
