# Generated by Django 4.1.2 on 2022-11-11 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_rename_customer_user_coupon_user'),
        ('userapp', '0015_alter_ordertable_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordertable',
            name='coupon',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.coupen'),
        ),
    ]
