# Generated by Django 4.1.2 on 2022-11-11 12:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0017_rename_customer_user_coupon_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('userapp', '0016_ordertable_coupon'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.FloatField(default=0)),
                ('is_paid', models.BooleanField(default=False)),
                ('order_id', models.CharField(blank=True, max_length=100)),
                ('payment_method', models.CharField(choices=[('COD', 'Cash On Delivery'), ('RAZORPAY', 'Razor Pay'), ('PAYPAL', 'Paypal')], default='COD', max_length=100)),
                ('payment_id', models.CharField(blank=True, max_length=100)),
                ('name', models.CharField(blank=True, max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=100)),
                ('house_name', models.CharField(blank=True, max_length=100)),
                ('street_name', models.CharField(blank=True, max_length=100)),
                ('landamrk', models.CharField(blank=True, max_length=100)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('pincode', models.CharField(blank=True, max_length=100)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled')], default='Pending', max_length=100)),
                ('message', models.TextField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tracking_no', models.CharField(default='none', max_length=100)),
                ('date_delivered', models.DateField(default='2022-01-01')),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adminapp.coupen')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
