# Generated by Django 4.1.2 on 2022-11-11 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0018_orderitemsample'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitemsample',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userapp.ordersample'),
        ),
    ]
