# Generated by Django 4.1.2 on 2022-11-15 05:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0020_address_default_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordersample',
            name='coupon',
        ),
        migrations.RemoveField(
            model_name='ordersample',
            name='user',
        ),
        migrations.DeleteModel(
            name='OrderItemSample',
        ),
        migrations.DeleteModel(
            name='OrderSample',
        ),
    ]
