# Generated by Django 4.1.2 on 2022-11-16 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userapp', '0021_remove_ordersample_coupon_remove_ordersample_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordertable',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Confirmed', 'Confirmed'), ('Delivered', 'Delivered'), ('Completed', 'Completed'), ('Rejected', 'Rejected'), ('Canceled', 'Canceled'), ('Returned', 'Returned')], default='Pending', max_length=100),
        ),
    ]
